name: webitel_sdk
description: "Webitel SDK Test App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.5
  sqflite: ^2.3.3
  bloc: ^8.1.4
  device_info_plus: ^10.1.0
  bloc_concurrency: ^0.2.5
  equatable: ^2.0.5
  uuid: ^4.4.0
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10+1
  build_runner: ^2.4.9
  path: ^1.9.0
  get_it: ^7.7.0
  package_info_plus: ^7.0.0
  webitel_sdk_package:
    path: webitel_sdk_package/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^3.0.2


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/send_message.svg



