name: webitel_sdk
description: "Webitel Portal SDK Demo App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.5
  sqflite: ^2.3.3+1
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  path_provider: ^2.1.3
  equatable: ^2.0.5
  uuid: ^4.4.0
  mime: ^1.0.5
  shared_preferences: ^2.2.3
  very_good_infinite_list: ^0.7.1
  flutter_svg: ^2.0.10+1
  build_runner: ^2.4.9
  path: ^1.9.0
  get_it: ^7.7.0
  file_picker: ^8.0.3
  webitel_portal_sdk:
    git:
      url: https://github.com/webitel/mobile-sdk-flutter.git
      ref: v1.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^3.0.2


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Bebas
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
          weight: 400