name: webitel_sdk
description: "Webitel SDK Test App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.5
  uuid: ^4.3.3
  flutter_svg: ^2.0.10+1
  build_runner: ^2.4.9
  get_it: ^7.6.8
  webitel_sdk_package:
    path: webitel_sdk_package/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^3.0.2


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/send_message.svg



