name: webitel_sdk_package
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.3

dependencies:
  build_runner: ^2.4.9
  fixnum: ^1.1.0
  get_it: ^7.6.8
  shared_preferences: ^2.2.2
  grpc: ^3.2.4
  protobuf: ^3.1.0
  uuid: ^4.3.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
